# .github/workflows/react-ci.yml
name: Blog UI App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies the safe way
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install specific Rollup dependencies
        run: npm install @rollup/rollup-linux-x64-gnu

      - name: Check style
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist/
          retention-days: 7

  # Add this job if you want to deploy to a hosting service
  # deploy:
  #   needs: build-and-test
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: react-build
  #         path: dist
  #
