# .github/workflows/react-ci.yml
name: React App CI/CD

on:
  push:
    branches:
      - main
    # paths:
    #   - "blog-ui/**"
  # pull_request:
  #   branches: [main, master, develop]
  #   paths:
  #     - "blog-ui/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./blog-ui

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./blog-ui/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./blog-ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: blog-ui/dist/

  # Add this job if you want to deploy to a hosting service
  # deploy:
  #   needs: build-and-test
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: react-build
  #         path: dist
  #
  #     - name: Deploy to hosting service
  #       # Add deployment steps based on your hosting provider
  #       # For example, for Firebase:
  #       # uses: FirebaseExtended/action-hosting-deploy@v0
  #       # with:
  #       #   repoToken: '${{ secrets.GITHUB_TOKEN }}'
  #       #   firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
  #       #   projectId: your-firebase-project-id
  #       #   channelId: live
